### ISSUE TITLE
can't set the expiration time for set / list / Zset / hash yet?

### ISSUE THREAD

**Issue by arden** [flower-corp/rosedb#106]
Now, can't set the expiration time for set / list / Zset / hash yet?

**Comment by roseduan** [comment]
Yes, we didn`t add this command right now, maybe in the near future.
If you want to use rosedb in production, I can take the time to add it, or you are just interested in how to implement it, you can contribute to rosedb, see https://github.com/flower-corp/rosedb/issues/103

**Comment by arden** [comment]
i want to use rosedb in production.

**Comment by roseduan** [comment]
Which data structure is most urgently needed, or all of them?
