### ISSUE TITLE
why mu is defined as the pointer type *sync. RWMutex in listIndex structs ?

### ISSUE THREAD

**Issue by eventian** [flower-corp/rosedb#143]
For structs in the project, such as "listIndex or hashIndex", mu is defined as the pointer type *sync. RWMutex, in the project mu is defined as is there anything wrong with  sync.RWMutex(e.g. sync. RWMutex copy problem)?

**Comment by roseduan** [comment]
we can reuse the mutex by defining it as a pointer(but we didn`t use it like that)

**Comment by eventian** [comment]
I still don't understand whether  sync.RWMutex be used instead of *sync. RWMutex, and if so, there will be something wrong with it ?

**Comment by roseduan** [comment]
Actually, they are no differences when using, but we can assign *sync. RWMutex to another variable to reuse it.

**Comment by eventian** [comment]
Got it, thanks a lot.
