### ISSUE TITLE
您好，请问您后续有考虑开发其他语言版本的rosedb吗

### ISSUE THREAD

**Issue by einQimiaozi** [flower-corp/rosedb#147]
我对kv数据库比较感兴趣，目前希望能够基于rust开发一个kv数据库，看了您的项目很感兴趣，希望能够基于当前的golang版本开发一个rust版本的rosedb

**Comment by roseduan** [comment]
自己倒没有这方面的想法了，对 rust 不太熟悉，只不过感兴趣的话你可以试试
通用的技术细节有问题可以一起交流
