### ISSUE TITLE
Why the func is legal

### ISSUE THREAD

**Issue by Reid00** [flower-corp/rosedb#151]
https://github.com/flower-corp/rosedb/blob/4a3aa6540cd8c043886aee5f9b425245860ad335/util/hash.go#L7
I have no idea why this func define is legal? there is no alias for it, how it work?

**Comment by Roderland** [comment]
`//go:linkname runtimeMemhash runtime.memhash`
@Reid00  This is a link of "runtime.memhash".

**Comment by Reid00** [comment]
In fact, I saw this comment, but I still have no idea the principal, do you have any resource I can refer to to understand it?

**Comment by Reid00** [comment]
got some information. close the issue.
