### ISSUE TITLE
About the sorting order of the Sorted Set

### ISSUE THREAD

**Issue by icemint0828** [flower-corp/rosedb#168]
**Describe the bug**

I think the order of the members when they have the same key and the same score is wrong.
https://redis.io/commands/zrange/
> The order of elements is from the lowest to the highest score. Elements with the same score are ordered lexicographically.

Attached a screenshot.
On the left is rosedb and on the right is redis.

<img src="https://user-images.githubusercontent.com/89819001/174001998-cab92cf2-56ac-428b-91b2-905cb381507b.png" width = "400px">

**Expected behavior**
To work like redis.

**Comment by roseduan** [comment]
We store the hash value of each member, so we can not guarantee the order of members when their scores are the same.

**Comment by icemint0828** [comment]
It's ok.
Thank you for your research.

Describe your proposal and close issue.

> This problem is not urgent, because it only happens when the scores are the same. Maybe most users don`t care about it.
> There is a simple way to solve it: sort the members manually after we get all of them.
> We can fix it when some users encounter it.
