### ISSUE TITLE
empty database with example tutorial key value store has 512M file

### ISSUE THREAD

**Issue by hiqsociety** [flower-corp/rosedb#169]
why does the rosedb database folder show 512mb but total is <12kb or something?

drwxr-xr-x 2 root root  126 Jun 16 11:04 DISCARD
-rw-r--r-- 1 root root    0 Jun 16 11:04 FLOCK
-rw-r--r-- 1 root root 512M Jun 16 11:05 log.strs.000000000

**Comment by roseduan** [comment]
Each log file size is preallocated when created, 512MB is the default value, you can change it by option `LogFileSizeThreshold`
