### ISSUE TITLE
退出GC程序的signal信号问题

### ISSUE THREAD

**Issue by Yukino831143** [flower-corp/rosedb#172]
**Describe the bug**
https://github.com/flower-corp/rosedb/blob/main/db.go#L490
```go
signal.Notify(quitSig, os.Interrupt, os.Kill, syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT)
```
问题：监听的信号`os.Interrupt` `syscall.SIGINT`存在重复

**To Reproduce**
NA

**Expected behavior**
NA

**Additional context**
NA

**Comment by roseduan** [comment]
是的，还有 `cmd/server.go` 里面也有

**Comment by roseduan** [comment]
Ceate a PR if you want

**Comment by Yukino831143** [comment]
ok
