### ISSUE TITLE
lpop or rpop命令每删除一个数据，发送两次discard数据到discard文件

### ISSUE THREAD

**Issue by Yukino831143** [flower-corp/rosedb#184]
**Describe the bug**
https://github.com/flower-corp/rosedb/blob/main/list.go#L381
```go
	if err = db.saveListMeta(idxTree, key, headSeq, tailSeq); err != nil {
		return nil, err
	}
	// send discard
	db.sendDiscard(oldVal, updated, List)                                                 // 第一次发送到discard
	_, entrySize := logfile.EncodeEntry(ent)
	node := &indexNode{fid: pos.fid, entrySize: entrySize}
	select {
	case db.discards[List].valChan <- node:                                           // 第二次发送到discard
	default:
		logger.Warn("send to discard chan fail")
	}
```
我认为删除一条entry数据，仅需要发送一次discard文件，因此我想仅保存`db.sendDiscard(oldVal, updated, List)  `，此处是否为一个bug？
**To Reproduce**
NA

**Expected behavior**
NA

**Additional context**
NA

**Comment by Yukino831143** [comment]
@Roderland 
1. list元数据本来也是单独存的一个entry，所以旧的元数据被回收无可厚非
2. discard文件的作用好像只是记录了各个文件无效数据的比率，不影响回收。
3. 如果说我只发送一次数据discard文件，感觉也不会影响这条数据的回收

**Comment by roseduan** [comment]
主要就是 @Roderland  说的第三点，“删除”这条log本身在垃圾回收中要被回收
所以也需要在 discard 文件中记录

其他的地方也类似，比如 Delete

**Comment by Yukino831143** [comment]
@roseduan @Roderland 谢谢两位解答
