### ISSUE TITLE
请问为什么要对/tmp/rosedb/FLOCK加flock锁

### ISSUE THREAD

**Issue by yanxiaoqi932** [flower-corp/rosedb#206]
请问为什么要对/tmp/rosedb/FLOCK加flock锁，这个文件并不参与任何数据读写，代码版本为rosedb-1.1.1

**Comment by yanxiaoqi932** [comment]
问题也许非常幼稚，但希望您能解答

**Comment by roseduan** [comment]
保证多进程的互斥，同一时间只允许一个进程在这个目录打开数据库

**Comment by yanxiaoqi932** [comment]
嗯我理解这个意思，但是我的疑问是为什么不直接对目录上flock锁，而是新建FLOCK文件并对这个文件上锁

**Comment by roseduan** [comment]
> 

嗯，达到的目的是一样的。没啥大的区别

**Comment by yanxiaoqi932** [comment]
明白了，谢谢解答
