### ISSUE TITLE
我应该怎么解决这个问题。github.com/roseduan/rosedb/cmd/proto 找不到

### ISSUE THREAD

**Issue by sober-wang** [flower-corp/rosedb#74]
![image](https://user-images.githubusercontent.com/35804630/145390469-7f322db3-91c0-46bb-af4e-d39dcda1025e.png)

windows 环境下怎么安装 protobuf 环境呢？
我之前做 grpc 实验安装过 protobuf ，我应该怎么复用它。

**Comment by roseduan** [comment]
执行一下 gen_pb_go.sh 这个脚本

**Comment by sober-wang** [comment]
我写了一篇 protocbuf 适配文档，希望能够帮助后来者：

https://www.cnblogs.com/shangmo/p/15671528.html
