### ISSUE TITLE
mmap写文件，每个文件只有一个entry

### ISSUE THREAD

**Issue by k-si** [flower-corp/rosedb#75]
### bug现象：
使用mmap方式set一个kv，在0.data.str文件中会写入一个二进制entry；再次使用mmap set一个kv，该kv会写入1.data.str文件的开头，而不是继续在0.data.str中继续写入。
这导致16mb的0.data.str文件中，只有一个entry，剩余绝大部分空间都没有使用。并且每set一次不同的k，就会多一个文件。

### bug原因：
文件offset数值错误。这发生在NewDBFile方法中的mmap逻辑中：
一开始我们让offset相当于文件的大小，但其实Truncate会将文件以'\0'填满，所以对于mmap来说，offset永远指的是文件固定大小，而不是实际entry要存储的位置。
由于存储逻辑中，会根据offset判断文件容量达到上限创建新文件存储entry，这就导致set新的k，会创建新的文件。
```golang
stat, err := file.Stat()
	if err != nil {
		return nil, err
	}

	df := &DBFile{Id: fileId, Path: path, Offset: stat.Size(), method: method}

	if method == FileIO {
		df.File = file
	} else {
		if err = file.Truncate(blockSize); err != nil {
			return nil, err
		}
		m, err := mmap.Map(file, os.O_RDWR, 0)
		if err != nil {
			return nil, err
		}
		df.mmap = m
	}
```

**Comment by k-si** [comment]
在构建索引时，是一个个文件遍历的，我想我可以在读取完所有entry后更新该文件的offset。这样就能保证mmap的offset指向真实entry的末尾。但是感觉实现起来并不是很优雅。

**Comment by roseduan** [comment]
感谢指正，目前按照你说的这样改是比较直观的，读完 Entry 再更新 offset。
实际上只需要更新最近的文件即可。
