### ISSUE TITLE
windows10  生成pb文件注意事项？

### ISSUE THREAD

**Issue by vaynedu** [flower-corp/rosedb#77]
环境
```
protoc-gen-go v1.27.1
protoc        v3.19.1
go1.173
```

windows生成pb文件命令
```
protoc --go-grpc_out=.  cmd/proto/rosedb.proto
protoc --go-grpc_out=.  cmd/proto/pb_set.proto
protoc --go-grpc_out=.  cmd/proto/pb_hash.proto
protoc --go-grpc_out=. cmd/proto/pb_zset.proto
protoc --go-grpc_out=.  cmd/proto/pb_str.proto
protoc --go-grpc_out=.  cmd/proto/pb_list.proto
```
高版本可能会遇到下面错误
![image](https://user-images.githubusercontent.com/11943184/146209573-ec4e8d50-0e68-4733-bb29-4c60b6a3de12.png)
参考文章
[grpc with mustEmbedUnimplemented*** method](https://stackoverflow.com/questions/65079032/grpc-with-mustembedunimplemented-method)
[mustEmbedUnimplemented*** method appear in grpc-server](https://github.com/grpc/grpc-go/issues/3794#issuecomment-725860916)
[protoc-gen-go-grpc: program not found or is not executable](https://stackoverflow.com/questions/60578892/protoc-gen-go-grpc-program-not-found-or-is-not-executable)

因此解决方案
```
protoc  --go-grpc_opt=require_unimplemented_servers=false --go-grpc_out=. cmd/proto/rosedb.proto
protoc --go-grpc_out=.  cmd/proto/rosedb.proto
protoc --go-grpc_out=.  cmd/proto/pb_set.proto
protoc --go-grpc_out=.  cmd/proto/pb_hash.proto
protoc --go-grpc_out=. cmd/proto/pb_zset.proto
protoc --go-grpc_out=.  cmd/proto/pb_str.proto
protoc --go-grpc_out=.  cmd/proto/pb_list.proto
```
![image](https://user-images.githubusercontent.com/11943184/146212926-115bf350-d928-4b40-8b09-5e142ecd1bf6.png)

**Comment by roseduan** [comment]
感谢，后续我会把这块加上，尽量不让大家手动去生成了
