### ISSUE TITLE
Docs referenced in README seem outdated

### ISSUE THREAD

**Issue by algermissen** [flower-corp/rosedb#85]
If I am not mistaken, the docs link on the README page points not to the latest docs.  Eg this change is not in the package docs

https://github.com/flower-corp/rosedb/commit/4385873cd876273752025aefa3afc79c8a48690c#diff-712e9efa3ee43d5b7429d9682aebe50c2011eeb91b7f8af793d9313df6cf9f02

Just so you know - great project, thanks a lot for this.

**Comment by roseduan** [comment]
Thanks, I will update it later. Or you can take a PR
