### ISSUE TITLE
merge不加锁么，merge的时机是啥时候啊，merge的时候是要完全停止读写么

### ISSUE THREAD

**Issue by yellowUmbrellaTM** [flower-corp/rosedb#89]
merge不加锁么，merge的时机是啥时候啊，merge的时候是要完全停止读写么

**Comment by roseduan** [comment]
不会停止读写，merge 的时机是自定义的，主要是对磁盘空间进行回收，看你能接收磁盘上有多少冗余数据

**Comment by yellowUmbrellaTM** [comment]
是merge的时候，是不merge当前active（正在写）的文件么？ 如果merge活跃文件，貌似没问题！这块没太看懂代码。如果活跃文件也merge的话应该有问题，因为没有双写机制，merge时，有写入就会丢数据吧？

**Comment by yellowUmbrellaTM** [comment]
多谢回复

**Comment by roseduan** [comment]
恩是的，不会 merge 当前最新的那个文件，这样写不会受到任何影响。
