### ISSUE TITLE
范围查询性能太差了吧

### ISSUE THREAD

**Issue by yellowUmbrellaTM** [flower-corp/rosedb#90]
bitdask模型应该只是时候用于大value，或者value存小文件的场景吧，而且就算用跳表做了索引，但是范围查询的时候，还是每个value的读取都是一次随机磁盘读，比mysql的“一次读一个页”到内存差很多啊，这样实现性能太差了，这样实现的话，感觉还不如退化成b+树的mysql呢

**Comment by roseduan** [comment]
的确有这种隐患，可以通过预读+多线程的方式去优化

**Comment by Sh-Zh-7** [comment]
应该说bitcask不适合range query场景。
