### ISSUE TITLE
Sharding for P2P model?

### ISSUE THREAD

**Issue by lonnietc** [flower-corp/rosedb#91]
Hello,

I have just come across RoseDB and think that it might be what I need for a project that I am working on.

One thing that I am needing is to develop for a P2P solution for the database with high number of nodes and am wondering about what it might take to have simple sharding added to RoseDB so that it can do high node clustering and spread out the data across all nodes as needed?

**Comment by lonnietc** [comment]
Also, I need to know if RoseDB can be compiled for different platforms? 

I need Linux, Mac, and Windows which Golang can do, but can RoseDB?

**Comment by roseduan** [comment]
rosedb is just a standalone kv storage engine, and it doesn`t care the upper applications, you need do it yourself.

By the way, test RoseDB  carefully before you decide to use it.

And tell us if there are problems, thanks.

**Comment by lonnietc** [comment]
Thanks for the information and I absolutely plan to test it really well.

I am planning on adding a P2P Chord layer that will allow RoseDB to run in a very high P2P cluster. At least that is the goal and will let you know if I come across an problems.

It would  be helpful to have a little bit more usage and example documentation on how to use some of the available commands since there are many and I do not know that parameters the take beyond the basic KV type like "set", "get" and did not see any "delete" either.

Can you please give me some more documentation so that I can utilize during my testing which will offer you beta testing results if I find problems?

Thanks again

**Comment by lonnietc** [comment]
Regarding documentation, I ran across some information that suggests that RoseDB is compatible (or mostly) with Redis DB.

If that is true then I have come across some basic documentation:

https://www.tutorialspoint.com/redis/index.htm

and

https://www.w3resource.com/redis/

I will have to look and see what Redis DB commands are not supported by RoseDb to get a better feel.

It seems that there are some differences:

RoseDB has:
1. Zset -- not sure what this does.

RedisDB has:
1.  Keys, Sorted Sets, HyperLogLog, Publish Subscribe, Transactions, Scripting, Connections

Both Redis DB and RoseDB have:

Strings, Lists, Hash, and Sets --- Not sure if the sub-commands in each of these are one-to-one or not.

**Comment by roseduan** [comment]
> Regarding documentation, I ran across some information that suggests that RoseDB is compatible (or mostly) with Redis DB.
> 
> If that is true then I have come across some basic documentation:
> 
> https://www.tutorialspoint.com/redis/index.htm
> 
> and
> 
> https://www.w3resource.com/redis/
> 
> I will have to look and see what Redis DB commands are not supported by RoseDb to get a better feel.
> 
> It seems that there are some differences:
> 
> RoseDB has:
> 
> 1. Zset -- not sure what this does.
> 
> RedisDB has:
> 
> 1. Keys, Sorted Sets, HyperLogLog, Publish Subscribe, Transactions, Scripting, Connections
> 
> Both Redis DB and RoseDB have:
> 
> Strings, Lists, Hash, and Sets --- Not sure if the sub-commands in each of these are one-to-one or not.

Yes, rosedb`s commands are mostly mean the same thing with redis.
