### ISSUE TITLE
build problems

### ISSUE THREAD

**Issue by lonnietc** [flower-corp/rosedb#93]
Hello,

Using: go version go1.16 windows/amd64

I just tried to build RoseDB, but have errors:

C:\goprojects\src\RoseDB\test>go build cmd\server\main.go
cmd\grpc_server.go:6:2: no required module provides package github.com/roseduan/rosedb/cmd/proto; to add it:
        go get github.com/roseduan/rosedb/cmd/proto

C:\goprojects\src\RoseDB\test>go get github.com/roseduan/rosedb/cmd/proto
go get github.com/roseduan/rosedb/cmd/proto: no matching versions for query "upgrade"

**Comment by roseduan** [comment]
please pull and try again

**Comment by lonnietc** [comment]
Hello,

Thanks as it seems to compile now and I was able to start up the server.exe and cli.exe

I do not see where it is writing the disk files and also do not see an information on what flags and paths can be set on the server and cli applications.  This does not seem to be listed in the READ.ME or gitub site information.

Do you have documentation on this?

**Comment by lonnietc** [comment]
As an update, I did find the config.toml that helps with some of the server startup parameters.

Now if you can just give me more examples and details on the (String, List, Hash, Set, Zset) commands so that I will have the information on the parameters needed for each and what they do then that would be awesome.

Thanks agian.

**Comment by roseduan** [comment]
> Hello,
> 
> Thanks as it seems to compile now and I was able to start up the server.exe and cli.exe
> 
> I do not see where it is writing the disk files and also do not see an information on what flags and paths can be set on the server and cli applications. This does not seem to be listed in the READ.ME or gitub site information.
> 
> Do you have documentation on this?

Embedded use, you can specify a `DirPath` in Config when open a DB.
cli is just a tool to read and write data.

**Comment by roseduan** [comment]
> As an update, I did find the config.toml that helps with some of the server startup parameters.
> 
> Now if you can just give me more examples and details on the (String, List, Hash, Set, Zset) commands so that I will have the information on the parameters needed for each and what they do then that would be awesome.
> 
> Thanks agian.

You can find the usage in `xx_test.go` file
